"""The status index for `research/decisions.md` (#541).

The log is ~1,300 lines across 37 sections, and answering "what is the current rule for X" used to
mean reading all of it: there was no index, the sections are not in date order, two heading formats
were in use, and a decision's *status* was discoverable only by reading its body — in one of three
different notations (inline strikethrough, an `⚠️ AMENDED` prose block, a `### REVERSED` subheading).

So each section now carries a one-line `**Status:**` next to the prose it describes, and the index
table at the top is **generated from those lines** by `make decisions`. That direction matters:
`tests/test_decisions.py` fails on a stale table, so the index cannot drift from the log the way a
hand-maintained one would — the same contract `make strategy` and `make reports` have.

The status line is the source of truth; the table is a build artifact of it (the argument
`reports.py` makes for front matter — metadata lives beside what it describes).
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

DECISIONS_MD = Path(__file__).resolve().parents[2] / "research" / "decisions.md"

BEGIN = "<!-- BEGIN DECISION INDEX (generated by `make decisions` — do not edit by hand) -->"
END = "<!-- END DECISION INDEX -->"

#: `## D-07 — Topic (2026-07-03, #122)` — the one heading format. The date group is anchored to the
#: end of the line, so a topic may contain its own parentheses.
HEADING = re.compile(r"^## D-(\d{2}) — (.+) \((\d{4}-\d{2}-\d{2})(?:, (.+))?\)$")

#: `**Status:** LIVE — amended #476` — one keyword, then an optional free-text note.
STATUS = re.compile(r"^\*\*Status:\*\* (LIVE|SUPERSEDED|REVERSED)(?: — (.+))?$")

STATES = ("LIVE", "SUPERSEDED", "REVERSED")


@dataclass(frozen=True)
class Decision:
    """One `##` section of the log."""

    id: str
    topic: str
    date: str
    refs: str
    state: str
    note: str

    @property
    def heading(self) -> str:
        """The heading this was parsed from, rebuilt — so the anchor is always its slug."""
        tail = f"{self.date}, {self.refs}" if self.refs else self.date
        return f"## D-{self.id} — {self.topic} ({tail})"

    @property
    def anchor(self) -> str:
        """The GitHub heading slug, so the index row links to the section."""
        return slug(self.heading.removeprefix("## "))

    @property
    def status(self) -> str:
        return f"{self.state} — {self.note}" if self.note else self.state


def slug(heading: str) -> str:
    """GitHub's heading slug: lowercase, drop punctuation, spaces to hyphens.

    Only the subset the heading grammar can actually produce is handled — em-dashes, parentheses,
    commas, `#`, `/` and periods. `tests/test_decisions.py` pins that every generated anchor is the
    slug of a real heading and that no two collide.
    """
    text = heading.lower()
    text = re.sub(r"[^\w\- ]", "", text)
    return text.replace(" ", "-")


def parse(text: str) -> list[Decision]:
    """Read every `## D-nn` section and the `**Status:**` line under it.

    Raises on a heading that doesn't match the grammar, or a section with no status line — a
    section the index silently skipped would be exactly the invisible-status problem again.
    """
    lines = text.splitlines()
    out: list[Decision] = []
    for i, line in enumerate(lines):
        if not line.startswith("## "):
            continue
        heading = HEADING.match(line)
        if heading is None:
            raise ValueError(
                f"decisions.md:{i + 1}: heading does not match the one format "
                f"`## D-nn — Topic (YYYY-MM-DD[, refs])`:\n  {line}"
            )
        body = [nxt for nxt in lines[i + 1 :] if nxt.strip()]
        status = STATUS.match(body[0]) if body else None
        if status is None:
            raise ValueError(
                f"decisions.md:{i + 1}: no `**Status:** {'|'.join(STATES)}` line under "
                f"`{line.strip()}` — status has to be answerable without reading the body."
            )
        out.append(
            Decision(
                id=heading.group(1),
                topic=heading.group(2),
                date=heading.group(3),
                refs=heading.group(4) or "",
                state=status.group(1),
                note=status.group(2) or "",
            )
        )
    return out


def render(decisions: list[Decision]) -> str:
    """The index table, between the generated-block markers."""
    rows = [
        f"| [D-{d.id}](#{d.anchor}) | {d.date} | {d.topic} | {d.refs or '—'} | {d.status} |"
        for d in decisions
    ]
    return "\n".join(
        [
            BEGIN,
            "",
            "| ID | Date | Decision | Issues | Status |",
            "|---|---|---|---|---|",
            *rows,
            "",
            END,
        ]
    )


def build(text: str) -> str:
    """Splice a freshly-rendered index into the log, replacing the previous one."""
    start, end = text.index(BEGIN), text.index(END) + len(END)
    return text[:start] + render(parse(text)) + text[end:]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m small_cap_stack.decisions")
    parser.add_argument("--path", type=Path, default=DECISIONS_MD, help=f"default: {DECISIONS_MD}")
    sub = parser.add_subparsers(dest="cmd", required=True)
    cmd = sub.add_parser("build", help="rewrite the index block from the section status lines")
    cmd.add_argument(
        "--check", action="store_true", help="don't write; exit non-zero if the index is stale"
    )

    args = parser.parse_args(argv)
    text = args.path.read_text()
    rebuilt = build(text)

    if args.check:
        if rebuilt == text:
            print(f"{args.path} is up to date")
            return 0
        print(f"{args.path} is STALE — run `make decisions`")
        return 1

    args.path.write_text(rebuilt)
    print(
        f"{'rewrote' if rebuilt != text else 'no change to'} {args.path} "
        f"({len(parse(text))} decisions)"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    raise SystemExit(main())
