#!/usr/bin/env bash
# Post a markdown file as a comment on a GitHub issue. Usage: ledger-post.sh <issue#> <file.md>
set -euo pipefail
issue="$1"; file="$2"
python3 - "$file" > /tmp/_ledger.json <<'PY'
import json, sys
body = open(sys.argv[1]).read().rstrip() + "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n"
print(json.dumps({"body": body}))
PY
curl -sS -X POST \
  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
  -H "Accept: application/vnd.github+json" \
  -H "Content-Type: application/json" \
  "https://api.github.com/repos/bennetwi92/small-cap-stack/issues/${issue}/comments" \
  --data-binary @/tmp/_ledger.json \
  | python3 -c 'import sys,json; d=json.load(sys.stdin); print(d.get("html_url") or d)'
